### PR TITLE
Feature/improve camp application

### PR DESCRIPTION
**Pull request by diegosteiner**
# Problem

Before hitobito, camp_applications had a more formal look & feel to them and could be used as documents to show municipality officials.

# Solution 

Polish the PDF with logos and denser layout to make it more like it was before

### CODE REVIEW

**Comment by diegosteiner** [comment]
Failing CI seems to be unrelated to these changes. Please rerun.

**Comment by RolandStuder** [comment]
@diegosteiner Am I correct to assume you consider the reworked camp application as done (no longer WIP)? So should we review it when we can, or will you add changes?

**Comment by diegosteiner** [comment]
Was fehlt hier noch damit das gemerged werden kann?

**Comment by carlobeltrame** [comment]
Vielen Dank für dieses schon lange geforderte Feature! In Zukunft könnte man sich vielleicht noch überlegen, Informationen über das Übergeordnete Lager anzugeben (falls eines existiert).

**Pull request merged**
