### PR TITLE
#252 Changed permission of Adressverwalter*in in Abteilung 

### PR DESCRIPTION
**Pull request by philobr**
Changed s.t. Adressverwalter*in can answer requests and access people without roles.

### CODE REVIEW

**Review by carlobeltrame — CHANGES_REQUESTED** [review]
Spec failures are unrelated.
Could you update the roles in the README with the output of `rake app:hitobito:roles`?

**Comment by Michael-Schaer** [comment]
Offizielles OK: Die Änderung passt für uns!

Merci @philobr

**Comment by philobr** [comment]
> Spec failures are unrelated. Could you update the roles in the README with the output of `rake app:hitobito:roles`?

done

**Review by carlobeltrame — APPROVED** [review]
Thank you for the contribution!

**Pull request merged**
