### PR TITLE
Allow Users with Role "Adressverwaltung" to edit users of the same group and it's children.

### PR DESCRIPTION
**Pull request by amadeous**
Allow Users with Role "Adressverwaltung" to edit users of the same
group and it's children.

### CODE REVIEW

**Comment by amadeous** [comment]
This pull request is the same than #1 with the wanted modifications.

**Comment by amadeous** [comment]
Can someone have a look at my pr and moderate it ?
I'm being asked when this modification will be effective.

**Comment by olibrian** [comment]
Question: the File change in "app/models/group/abteilung.rb" has as far as I know no influence. The "Adressverwalter" as on every other layer the permission ":layer_and_below_full". So in case of consequent I would suggest to leave this permission it as it is.

**Comment by amadeous** [comment]
Do I need to re-set "Adressverwalter" with ":layer_and_below_full" as it was If this modification has no influence ?
Leaving this permission as it is can be seen as a way to uniform the permission name, if those two permission (group_and_below_full and layer_and_below_full) are identical.

**Comment by RolandStuder** [comment]
Thanks, we will integrate this the next time, we touch PBS stuff.

**Comment by RolandStuder** [comment]
@adriananderegg Ich schlage vor dass wir diesen Pull Request endlich auch noch integrieren. Erweitert einfach die Rechte von Adressverwaltern, dass er immer auch Subgruppen editieren kann. (was er kurioserweise heute noch nicht kann).

Ok?

**Comment by adriananderegg** [comment]
ok

**Comment by amadeous** [comment]
Thanks !
When do you think it would be done ?

**Comment by RolandStuder** [comment]
We will probably have a release in January where we will include this. Sorry for the delay.

**Pull request merged**
